apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
  namespace: coolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapi"
  template:
    metadata:
      labels:
        app: "coolapi"
    spec:
      containers:
        - name: "coolapi"
          image: "acrpierrc007.azurecr.io/coolapi:1.0.0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          
